// 운동 데이터베이스 — 맨몸/샌드백/섀도우/스파링 중심, 기구 웨이트 제외
// 각 운동: id, name, category, venue, level, focus, cue, description, steps[], mistakes[], imgQuery

window.EXERCISES = [
  // ---- WARMUP
  {
    id: 'jump_rope', name: '줄넘기', category: 'warmup', venue: 'gym', level: 'beginner',
    focus: '심박수/풋워크', cue: '가볍게 발끝으로, 어깨 힘 빼고 손목 스냅으로 돌리기',
    description: '복싱의 시그니처 워밍업. 발목·종아리·손목을 깨우면서 라운드 타이밍에 익숙해지게 만든다.',
    steps: [
      '발뒤꿈치를 바닥에 닿지 않게, 발끝만 사용해 탄성 있게 뛴다.',
      '어깨·팔꿈치는 고정. 손목 스냅만으로 줄을 돌린다.',
      '턱은 당기고 시선은 정면. 가드 자세와 비슷하게 유지.',
      '3분 한 라운드 기준. 처음 30초는 감각 찾기, 후반은 속도·패턴 변형.',
    ],
    mistakes: ['팔 전체로 돌리기 → 어깨 피로', '뒤꿈치 착지 → 무릎·발목 부상', '턱이 들리고 시선이 떨어짐'],
    imgQuery: 'jump rope boxing',
  },
  {
    id: 'dynamic_stretch', name: '동적 스트레칭', category: 'warmup', venue: 'both', level: 'beginner',
    focus: '가동성', cue: '목·어깨·허리·고관절 순서로 크게 원을 그리며 풀어주기',
    description: '정적 스트레칭 대신 움직이며 근육 온도와 관절 가동 범위를 늘린다. 훈련 전 필수.',
    steps: [
      '목 회전 5회씩 좌우. 천천히 큰 원.',
      '양팔 앞으로 큰 원 10회, 뒤로 10회.',
      '허리 회전 좌우 10회. 손은 허리에.',
      '다리 흔들기 앞뒤/좌우 각 10회씩.',
      '레그 스윙, 깊은 런지 워크 5걸음.',
    ],
    mistakes: ['반동 사용해 갑자기 당기기 — 부상 위험', '호흡 멈추기', '통증이 느껴지는 범위까지 밀어붙이기'],
    imgQuery: 'dynamic stretching warm up',
  },
  {
    id: 'neck_rolls', name: '목·어깨 풀기', category: 'warmup', venue: 'both', level: 'beginner',
    focus: '부상 예방', cue: '천천히, 절대 반동 주지 말고 통증 없는 범위까지만',
    description: '펀치를 맞을 부위인 목·승모근·삼각근을 미리 풀어 부상을 줄인다.',
    steps: [
      '고개를 한 방향으로 천천히 원을 그린다 — 5회, 반대 5회.',
      '양쪽 어깨를 귀 쪽으로 올렸다가 뒤로 돌리며 떨어뜨리기 10회.',
      '한 손으로 반대쪽 머리를 가볍게 당겨 측면 목 스트레칭 각 15초.',
      '견갑골을 조였다 펴기 — 등 근육을 깨운다.',
    ],
    mistakes: ['목을 뒤로 젖힌 채 회전 — 경추 압박', '숨 참고 하기', '너무 빠르게 돌리기'],
    imgQuery: 'neck shoulder warm up',
  },
  {
    id: 'shoulder_rolls', name: '숄더 롤 드릴', category: 'warmup', venue: 'both', level: 'beginner',
    focus: '방어', cue: '잽을 맞는다는 상상으로 양 어깨 교대로 턱 쪽으로 말아올리기',
    description: '상대의 잽·훅을 어깨로 흘리는 필립프리즘 스타일 방어의 기초 동작.',
    steps: [
      '복싱 스탠스로 선다. 가드 위치.',
      '앞쪽 어깨를 턱 쪽으로 살짝 들어올려 잽을 어깨 위로 흘리는 느낌.',
      '같은 방식으로 뒤쪽 어깨도 교대.',
      '어깨를 올릴 때 턱은 반대쪽 어깨 뒤로 살짝 숨기기.',
    ],
    mistakes: ['어깨 대신 팔을 드는 습관', '자세가 무너지면서 뒤로 젖혀짐', '리듬 없이 기계적으로 반복'],
    imgQuery: 'boxing shoulder roll defense',
  },

  // ---- SHADOW BOXING
  {
    id: 'shadow_tech', name: '섀도우 복싱 (기술)', category: 'shadow', venue: 'both', level: 'beginner',
    focus: '폼/정확도', cue: '거울 보며 잽-스트레이트 기본기. 속도보다 정확도',
    description: '빈 공간에서 자신과 싸우며 기본 펀치의 궤적·자세·밸런스를 점검한다. 복싱 훈련의 뿌리.',
    steps: [
      '거울 앞에 복싱 스탠스로 선다. 어깨 너비 + 반 발.',
      '잽: 앞손을 일직선으로 뻗고 반대손은 턱 방어.',
      '잽을 쏘자마자 같은 속도로 가드 복귀.',
      '잽-스트레이트: 잽 후 힙 회전으로 뒷손 스트레이트.',
      '3분 라운드 내내 한 콤보에 집중.',
    ],
    mistakes: ['어깨로 치지 않고 팔로만 치기', '턱을 노출한 채 주먹 뻗기', '힙 회전 없는 스트레이트'],
    imgQuery: 'shadow boxing technique',
  },
  {
    id: 'shadow_footwork', name: '섀도우 풋워크 드릴', category: 'shadow', venue: 'both', level: 'beginner',
    focus: '풋워크', cue: '사이드 스텝·피벗·인앤아웃. 무게 중심 낮게 유지',
    description: '거리 조절·각도 생성·위험 이탈의 근간. 발이 못 움직이면 아무리 좋은 주먹도 소용없다.',
    steps: [
      '스탠스 유지한 채 앞으로 2스텝 → 뒤로 2스텝.',
      '좌측 사이드 스텝 (앞발 먼저, 뒷발 따라오기) → 우측.',
      '피벗: 앞발을 축으로 45도 회전.',
      '인앤아웃: 잽 거리로 들어갔다가 즉시 빠지기.',
      '매 이동 후 스탠스 균형 체크.',
    ],
    mistakes: ['발을 꼬거나 벌어진 스탠스', '이동 중 가드 떨어짐', '체중이 뒷발로만 실림'],
    imgQuery: 'boxing footwork drill',
  },
  {
    id: 'shadow_combo', name: '섀도우 콤비네이션', category: 'shadow', venue: 'both', level: 'intermediate',
    focus: '연결', cue: '1-2, 1-2-3, 1-2-3-4 조합. 매 라운드 콤보 하나씩 추가',
    description: '단타가 아닌 연결의 훈련. 각 펀치가 다음 펀치의 셋업이 되도록 체중 이동을 조율한다.',
    steps: [
      '1-2 (잽-스트레이트): 체중을 앞발→뒷발 사이 센터로.',
      '1-2-3 (잽-스트레이트-리드 훅): 훅 때 체중을 뒷발로.',
      '1-2-3-2 (마지막에 스트레이트 다시): 리듬 변화.',
      '각 콤보 후 2스텝 이동 — 꽂은 자리에서 빠지기.',
      '30초씩 콤보 변경. 총 3-5분.',
    ],
    mistakes: ['마지막 펀치 후 가드 안 올림', '콤보가 길어질수록 자세 무너짐', '힙 회전 방향이 뒤섞임'],
    imgQuery: 'boxing combination shadow',
  },
  {
    id: 'shadow_slip', name: '슬립·위브 드릴', category: 'shadow', venue: 'both', level: 'intermediate',
    focus: '방어', cue: '상대 잽을 본다고 상상하고 좌우로 머리 움직임. 허리로 피하기',
    description: '주먹 궤적에서 머리를 1-2인치만 빼는 정교한 방어. 허리와 다리로 움직이며 가드는 유지.',
    steps: [
      '스탠스에서 무릎을 살짝 구부린다.',
      '슬립 좌: 체중을 왼발로 옮기며 상체를 왼쪽으로 기울인다 (잽 흘리기).',
      '슬립 우: 체중을 오른발로 옮기며 반대로.',
      '위브: 상체를 U자로 그리며 낮게 잠수.',
      '슬립-슬립-위브-카운터 패턴으로 연결.',
    ],
    mistakes: ['허리가 아닌 목만 움직임', '가드가 풀림', '체중 이동 없이 머리만 기울임'],
    imgQuery: 'boxing slip weave defense',
  },
  {
    id: 'shadow_counter', name: '카운터 드릴', category: 'shadow', venue: 'both', level: 'advanced',
    focus: '반격', cue: '슬립 후 즉시 카운터. 방어-공격 한 동작으로 연결',
    description: '상대 펀치를 피하자마자 체중 이동을 그대로 살려 반격. 타이밍과 거리감의 정점.',
    steps: [
      '가상의 잽을 본다 → 슬립 우.',
      '슬립과 동시에 왼쪽 스트레이트를 상대 턱 라인으로.',
      '슬립 좌 → 오른쪽 훅 to body.',
      '위브 → 어퍼컷.',
      '3-5 패턴을 루프로 연결.',
    ],
    mistakes: ['방어 따로 공격 따로 — 박자 놓침', '너무 크게 슬립해서 반격 타이밍 놓침', '카운터 펀치에 힘이 안 실림'],
    imgQuery: 'boxing counter punch',
  },
  {
    id: 'shadow_power', name: '섀도우 파워 라운드', category: 'shadow', venue: 'both', level: 'intermediate',
    focus: '출력', cue: '매 펀치 전력. 힙 로테이션과 발 회전에 집중',
    description: '샌드백 없이도 파워 훈련이 가능하다. 빈 공간을 향해 전력 펀치를 던지되 어깨·팔꿈치 과신전을 조심.',
    steps: [
      '각 펀치 전 숨을 짧게 내쉰다 ("츳" 소리).',
      '뒷발 뒤꿈치를 돌려 힙과 코어를 연결.',
      '펀치 끝에서 완전 신전하지 말고 90-95%에서 멈춤.',
      '한 번 치고 반드시 가드 복귀.',
      '라운드당 20-30개만. 양보다 질.',
    ],
    mistakes: ['팔꿈치 완전 락아웃 — 관절 부상', '숨 참기', '뒷발 고정된 채 팔만 휘두름'],
    imgQuery: 'boxing power punch shadow',
  },

  // ---- HEAVY BAG
  {
    id: 'bag_jab', name: '잽 드릴 (샌드백)', category: 'bag', venue: 'gym', level: 'beginner',
    focus: '기본기', cue: '한 라운드 내내 잽만. 리듬과 거리 조절 연습',
    description: '잽은 복싱의 알파벳. 거리 측정·견제·셋업 모든 것의 시작. 이 한 펀치가 좋아야 나머지가 따라온다.',
    steps: [
      '샌드백에서 잽이 80% 신전되는 거리에 선다.',
      '어깨로 밀어치되 턱은 뒤쪽 어깨에 붙여 방어.',
      '잽을 쏠 때 같은 속도로 회수 — "고무줄처럼".',
      '리듬 변화: 더블 잽, 스텝 잽, 후퇴 잽.',
      '3분 내내 잽. 지루할 만큼.',
    ],
    mistakes: ['주먹을 내려놓고 치는 "텔레그래프 잽"', '손목이 꺾인 채 닿음', '팔꿈치가 바깥으로 벌어짐'],
    imgQuery: 'heavy bag jab',
  },
  {
    id: 'bag_1_2', name: '원-투 콤비 (샌드백)', category: 'bag', venue: 'gym', level: 'beginner',
    focus: '기본 콤보', cue: '잽으로 거리 맞추고 스트레이트 힙으로 꽂기',
    description: '가장 많이 쓰이는 콤보. 잽이 길을 열고 스트레이트가 피니시한다.',
    steps: [
      '잽을 먼저 쏘며 상대 가드·거리 확인.',
      '잽 회수 동시에 뒷발을 살짝 밀어 스트레이트 준비.',
      '뒷발 힙 회전을 최대로 활용해 스트레이트.',
      '스트레이트가 꽂힐 때 반대쪽 손은 반드시 턱 방어.',
      '빠져나올 때는 사이드 스텝으로 각도 바꾸기.',
    ],
    mistakes: ['잽과 스트레이트가 같은 라인 — 카운터 맞기 쉬움', '스트레이트 후 가드 복귀 지연', '앞발에 체중이 몰림'],
    imgQuery: 'heavy bag one two combination',
  },
  {
    id: 'bag_combo', name: '콤비네이션 라운드', category: 'bag', venue: 'gym', level: 'intermediate',
    focus: '연결', cue: '1-2-3-2, 1-2-5-2 등. 마지막 펀치 후 반드시 가드 복귀',
    description: '3개 이상의 펀치를 하나의 흐름으로 연결. 각 펀치가 다음 펀치를 위한 체중 이동이어야 한다.',
    steps: [
      '1-2-3: 잽-스트레이트-리드훅.',
      '1-2-5-2: 잽-스트레이트-리드 어퍼컷-스트레이트.',
      '1-1-2: 더블 잽 후 스트레이트.',
      '콤보별 30초씩 샌드백에 연속 적용.',
      '라운드 종료 10초 전 최대 출력 마무리.',
    ],
    mistakes: ['3번째 펀치부터 자세 무너짐', '펀치끼리 리듬이 끊김', '체중 이동 없이 팔만 움직임'],
    imgQuery: 'heavy bag combinations',
  },
  {
    id: 'bag_hooks', name: '훅 드릴 (샌드백)', category: 'bag', venue: 'gym', level: 'intermediate',
    focus: '측면 공격', cue: '좌우 훅 교대. 팔로만 치지 말고 허리와 다리 회전',
    description: '옆으로 휘어 들어가는 원형 궤적. 상대 가드 사이드를 뚫거나 간 부위를 노린다.',
    steps: [
      '팔꿈치를 어깨 높이까지 올린다 — 90도 각도.',
      '체중을 때리는 손과 반대쪽 발로 싣는다.',
      '허리-힙-어깨 순서로 회전하며 주먹이 따라간다.',
      '주먹이 샌드백에 닿는 순간 발뒤꿈치가 회전.',
      '왼훅 → 오른훅 교대, 30초씩.',
    ],
    mistakes: ['팔로만 휘두르는 "윈드밀"', '팔꿈치가 너무 낮거나 높음', '반대손 가드 풀림'],
    imgQuery: 'heavy bag hook punch',
  },
  {
    id: 'bag_uppercut', name: '어퍼컷 드릴', category: 'bag', venue: 'gym', level: 'intermediate',
    focus: '근거리', cue: '무릎 굽히고 다리로 밀어올리듯. 팔꿈치 바깥으로 새지 않게',
    description: '아래에서 위로 올라가는 펀치. 인파이팅과 상대가 숙였을 때의 무기.',
    steps: [
      '샌드백에 한 발 더 가까이 선다.',
      '무릎을 살짝 굽혀 몸을 낮춘다.',
      '주먹을 손바닥이 자신을 향하게 들고 다리 힘으로 밀어올림.',
      '팔꿈치는 몸통에 붙어 있어야 하고 위로만 이동.',
      '좌우 교대, 바디 어퍼컷과 헤드 어퍼컷 섞어 연습.',
    ],
    mistakes: ['팔꿈치가 밖으로 벌어진 "링 오버"', '몸을 숙이지 않고 팔로만 올림', '어퍼컷 후 가드 복귀 늦음'],
    imgQuery: 'heavy bag uppercut',
  },
  {
    id: 'bag_body', name: '바디샷 라운드', category: 'bag', venue: 'gym', level: 'intermediate',
    focus: '바디 공격', cue: '무릎 굽혀 자세 낮추고 리버·솔라플렉서스 타격',
    description: '상대의 체력을 깎는 무기. 머리보다 맞추기 쉽지만 자세를 낮춰야 하므로 카운터 위험이 있다.',
    steps: [
      '무릎을 굽혀 상체 높이를 샌드백 중단에 맞춘다.',
      '잽은 여전히 머리 라인, 스트레이트·훅은 바디로.',
      '좌훅 to body: 상대 간 부위를 노리듯 옆에서 파고듦.',
      '바디 후 즉시 머리로 올려치기 (body-head 연결).',
      '머리 가드는 절대 내리지 않기.',
    ],
    mistakes: ['바디 치려고 머리가 앞으로 나감', '한쪽만 계속 때림', '바디 후 일어서며 가드 풀기'],
    imgQuery: 'heavy bag body shot',
  },
  {
    id: 'bag_power', name: '파워 라운드 (샌드백)', category: 'bag', venue: 'gym', level: 'advanced',
    focus: '최대 출력', cue: '매 펀치 전력. 라운드당 10-15개만 치고 최대 파워로',
    description: '양보다 질. 모든 체중·힙·발뒤꿈치 회전을 한 펀치에 싣는 훈련.',
    steps: [
      '샌드백이 실제로 크게 흔들릴 만큼의 파워.',
      '펀치 사이 5-10초 여유를 두고 완전 리셋.',
      '뒷발 뒤꿈치 완전 회전 — "발뒤꿈치가 나와야 한다".',
      '숨을 짧고 강하게 내쉬며 타격.',
      '3분 중 타격 시간은 절반. 나머지는 거리·리셋.',
    ],
    mistakes: ['파워만 쫓다 자세 무너짐', '손목·어깨 부상 무시', '모든 펀치를 다 파워로 — 후반 효율 급락'],
    imgQuery: 'heavy bag power punch',
  },
  {
    id: 'bag_speed', name: '스피드 라운드 (샌드백)', category: 'bag', venue: 'gym', level: 'intermediate',
    focus: '스피드', cue: '가벼운 힘, 최대 속도. 손이 돌아오는 속도에 집중',
    description: '파워 대신 빈도. 손의 회수 속도가 핵심 — 치는 것보다 돌아오는 게 빨라야 한다.',
    steps: [
      '타격보다 "두드린다"는 감각.',
      '3-6 펀치 콤보를 짧게 반복.',
      '각 펀치 사이 쉬지 않음.',
      '라운드 내내 호흡 리듬 유지.',
      '마지막 30초 올아웃 스프린트.',
    ],
    mistakes: ['힘 실으려다 속도 놓침', '숨 거칠게 쉬기', '리듬 없이 아무렇게나 치기'],
    imgQuery: 'heavy bag speed drill',
  },
  {
    id: 'bag_move', name: '무빙 샌드백', category: 'bag', venue: 'gym', level: 'intermediate',
    focus: '풋워크+타격', cue: '샌드백 돌며 각도 바꿔 치기. 한 자리에 서지 말기',
    description: '실전에서는 상대도 움직인다. 샌드백을 상대 삼아 원을 그리며 공격 각도를 바꾸는 훈련.',
    steps: [
      '샌드백 주위를 천천히 원을 그리며 이동.',
      '이동 중간 멈춰서 콤보 → 다시 이동.',
      '시계 방향 30초, 반시계 30초 교대.',
      '사이드 스텝 잽을 적극 활용.',
      '빠져나올 때 45도 각도로 이탈.',
    ],
    mistakes: ['이동하며 자세가 벌어짐', '원을 그리는 게 아니라 직선으로만 왔다갔다', '타격 순간 정지하지 않음'],
    imgQuery: 'moving around heavy bag',
  },
  {
    id: 'bag_freestyle', name: '프리 라운드', category: 'bag', venue: 'gym', level: 'advanced',
    focus: '실전', cue: '시합처럼. 방어·무빙·공격 모두 섞어 자유롭게',
    description: '실전 시뮬레이션. 샌드백이 공격한다고 상상하며 슬립·위브·카운터·콤보를 자유롭게 섞는다.',
    steps: [
      '3분 라운드를 실제 경기처럼 진행.',
      '처음 1분: 거리 탐색 + 잽 위주.',
      '중간 1분: 콤보 + 카운터.',
      '마지막 1분: 올아웃 — 하지만 자세 유지.',
      '라운드 간 1분 휴식 — 실제 경기 인터벌.',
    ],
    mistakes: ['시나리오 없이 마구잡이', '방어 없이 공격만', '끝까지 페이스 조절 못함'],
    imgQuery: 'boxing freestyle heavy bag',
  },

  // ---- SPARRING
  {
    id: 'spar_light', name: '라이트 스파링', category: 'sparring', venue: 'gym', level: 'intermediate',
    focus: '실전 감각', cue: '파워 40%, 기술에 집중. 부상 조심하고 서로 존중',
    description: '실제 사람을 상대로 기술을 적용. 파워보다 타이밍·거리·방어 학습이 목적.',
    steps: [
      '풀 장비 착용: 헤드기어·마우스피스·16oz 글러브 권장.',
      '파트너와 파워 수준 합의.',
      '먼저 가볍게 잽만 교환하며 거리 감각.',
      '점차 콤보·방어 추가.',
      '라운드 종료 후 서로 피드백.',
    ],
    mistakes: ['감정적으로 격해짐', '파워 약속 어기기', '헤드 버트·팔꿈치 같은 반칙 동작'],
    imgQuery: 'light sparring boxing',
  },
  {
    id: 'spar_technical', name: '테크니컬 스파링', category: 'sparring', venue: 'gym', level: 'intermediate',
    focus: '기술 적용', cue: '미리 정한 기술만 사용 (예: 잽+카운터). 이기려 하지 말 것',
    description: '제한된 기술로만 싸우는 훈련 스파링. 약점을 노출하고 보완하는 데 최적.',
    steps: [
      '코치/파트너와 오늘의 주제 결정 (예: 잽+풋워크만).',
      '룰 위반 시 즉시 리셋.',
      '이기는 게 아니라 약속된 기술의 완성도 체크.',
      '라운드마다 주제 변경 가능.',
    ],
    mistakes: ['룰 무시하고 자기 주먹만 던짐', '이기려고 감정 이입', '피드백 거부'],
    imgQuery: 'technical sparring boxing',
  },
  {
    id: 'spar_position', name: '포지션 스파링', category: 'sparring', venue: 'gym', level: 'intermediate',
    focus: '특정 상황', cue: '로프·코너 등 한 상황 반복. 빠져나오기·몰아붙이기 훈련',
    description: '불리한 포지션(로프·코너)에서 시작해 탈출 또는 유리 포지션에서 마무리 연습.',
    steps: [
      '한 명은 코너/로프에서 시작.',
      '상대는 공격, 코너 선수는 방어·탈출.',
      '30-60초 후 역할 교체.',
      '탈출 시 반드시 각도 만들고 이탈.',
    ],
    mistakes: ['탈출 대신 그냥 버티기', '코너에서 얼굴 숙여 노출', '공격자가 파워 남발'],
    imgQuery: 'corner sparring boxing',
  },
  {
    id: 'spar_drill', name: '드릴 스파링 (정해진 패턴)', category: 'sparring', venue: 'gym', level: 'beginner',
    focus: '기본 교환', cue: '한 명이 공격, 한 명이 방어·카운터. 역할 번갈아',
    description: '스파링 입문자용. 공격/방어 역할을 명확히 나눠 안전하게 기술을 주고받는다.',
    steps: [
      '역할 분담: A 공격(잽-투), B 방어(파리·슬립).',
      '같은 패턴 10회 반복.',
      '역할 교체.',
      '익숙해지면 카운터 추가.',
    ],
    mistakes: ['역할 경계 무너짐', '파워 실수', '피드백 없이 그냥 진행'],
    imgQuery: 'boxing drill sparring',
  },

  // ---- BODYWEIGHT
  {
    id: 'pushup', name: '푸시업', category: 'bodyweight', venue: 'both', level: 'beginner',
    focus: '상체 푸시', cue: '몸 일직선, 팔꿈치 45도. 가슴이 바닥 닿을 듯이 내리기',
    description: '상체 푸시의 기본. 복서에게는 가슴·어깨 내구성과 펀치 파워의 기초.',
    steps: [
      '양손을 어깨 너비보다 약간 넓게 바닥.',
      '발끝·손바닥·코어로 몸을 일직선 유지.',
      '팔꿈치가 몸통과 45도 — 너무 벌어지면 어깨 부상.',
      '가슴이 주먹 하나 높이까지 내려오게.',
      '밀어올릴 때 가슴·삼두·코어를 함께 조인다.',
    ],
    mistakes: ['허리 처짐 또는 엉덩이 들림', '팔꿈치 90도로 벌어짐', '반만 내려갔다 올라옴'],
    imgQuery: 'push up exercise',
  },
  {
    id: 'pushup_diamond', name: '다이아몬드 푸시업', category: 'bodyweight', venue: 'both', level: 'intermediate',
    focus: '삼두', cue: '엄지·검지로 다이아 모양. 팔꿈치 몸통에 붙여 내리기',
    description: '삼두 집중 푸시업. 스트레이트 펀치의 마지막 신전 근육을 강화.',
    steps: [
      '양손 엄지와 검지를 모아 다이아몬드.',
      '손은 가슴 바로 아래.',
      '팔꿈치는 완전히 몸통에 붙여 내림.',
      '가슴이 손등에 닿을 듯이.',
    ],
    mistakes: ['팔꿈치 벌어짐', '엉덩이 들리며 상체로만 내림', '반만 내려감'],
    imgQuery: 'diamond push up',
  },
  {
    id: 'pushup_decline', name: '디클라인 푸시업', category: 'bodyweight', venue: 'both', level: 'intermediate',
    focus: '상부 흉근', cue: '발을 소파·의자 위. 어깨 부상 조심, 무게 실수 없이',
    description: '발을 올려 상부 흉근과 전면 삼각근을 더 자극. 난이도 상승.',
    steps: [
      '발을 벤치/의자 위에 올림 (30-50cm).',
      '손은 어깨 너비, 몸통 일직선.',
      '천천히 내렸다가 폭발적으로 밀어올림.',
      '고개는 들지 않고 시선 바닥.',
    ],
    mistakes: ['엉덩이만 올라감', '어깨에 과부하 — 먼저 표준 푸시업 숙달', '호흡 멈춤'],
    imgQuery: 'decline push up',
  },
  {
    id: 'pullup', name: '풀업', category: 'bodyweight', venue: 'gym', level: 'intermediate',
    focus: '등·이두', cue: '어깨 내리고 턱이 바 위로. 반동 없이 천천히 내려오기',
    description: '등 근육·이두의 최강 맨몸 운동. 복서의 풀백(팔 회수) 속도에 직결.',
    steps: [
      '손등이 앞을 향하게 바를 잡는다 (오버 그립).',
      '어깨를 아래로 끌어내린 후 당기기 시작.',
      '턱이 바를 넘어갈 때까지 당긴다.',
      '천천히 2-3초에 걸쳐 내린다.',
    ],
    mistakes: ['반동 사용 (킵핑)', '반만 올라감', '어깨가 귀까지 올라감 — 승모근만 사용'],
    imgQuery: 'pull up bar',
  },
  {
    id: 'chinup', name: '친업', category: 'bodyweight', venue: 'gym', level: 'beginner',
    focus: '이두·등', cue: '손등이 내 쪽. 풀업보다 쉬움, 풀업 못하면 여기부터',
    description: '이두 관여가 커서 풀업보다 쉽다. 풀업 진입의 징검다리.',
    steps: [
      '손바닥이 자신을 향하게 (언더 그립).',
      '손은 어깨 너비.',
      '견갑 내리고 이두·등으로 당김.',
      '턱이 바를 넘어가게.',
    ],
    mistakes: ['다리로 반동', '손목 꺾임', '내릴 때 갑자기 떨어짐'],
    imgQuery: 'chin up exercise',
  },
  {
    id: 'squat', name: '스쿼트', category: 'bodyweight', venue: 'both', level: 'beginner',
    focus: '하체', cue: '무릎이 발끝 방향. 허벅지가 바닥과 평행할 때까지 내리기',
    description: '복싱 파워의 원천은 다리. 모든 스트레이트·훅의 파워는 하체에서 나온다.',
    steps: [
      '발을 어깨 너비, 발끝 살짝 바깥.',
      '엉덩이를 뒤로 빼며 앉기 시작.',
      '무릎이 발끝 방향과 일치.',
      '허벅지가 바닥과 평행 or 그보다 낮게.',
      '뒤꿈치로 밀어 올라옴.',
    ],
    mistakes: ['무릎이 안쪽으로 모임', '뒤꿈치가 뜸', '상체가 너무 앞으로 숙여짐'],
    imgQuery: 'bodyweight squat',
  },
  {
    id: 'jump_squat', name: '점프 스쿼트', category: 'bodyweight', venue: 'both', level: 'intermediate',
    focus: '하체 파워', cue: '스쿼트 하단에서 폭발적으로 점프. 착지는 부드럽게',
    description: '하체의 폭발력 훈련. 풋워크 점프·카운터 이탈의 밑바탕.',
    steps: [
      '표준 스쿼트 자세로 내려감.',
      '하단에서 즉시 폭발적으로 점프.',
      '공중에서 몸은 일직선.',
      '착지는 발 앞쪽 → 뒤꿈치 순서로 부드럽게.',
      '착지 즉시 다음 스쿼트.',
    ],
    mistakes: ['착지 시 무릎 꺾임', '쿵쿵 착지 — 관절 부상', '상체가 앞으로 숙여진 상태로 점프'],
    imgQuery: 'jump squat exercise',
  },
  {
    id: 'lunge', name: '런지', category: 'bodyweight', venue: 'both', level: 'beginner',
    focus: '하체', cue: '앞무릎 90도, 뒷무릎이 바닥 닿기 직전까지. 상체 곧게',
    description: '복싱 스탠스와 유사한 단일 다리 훈련. 전후좌우 균형 감각을 키운다.',
    steps: [
      '한 다리를 앞으로 크게 내딛음.',
      '앞무릎 90도, 뒷무릎도 90도 가까이.',
      '뒷무릎이 바닥에 닿지 않을 만큼.',
      '앞발 뒤꿈치로 밀어 시작 자세.',
      '좌우 교대.',
    ],
    mistakes: ['앞무릎이 발끝을 넘어감', '상체가 숙여짐', '뒷무릎이 바닥에 꽝'],
    imgQuery: 'lunge exercise',
  },
  {
    id: 'jump_lunge', name: '점프 런지', category: 'bodyweight', venue: 'both', level: 'intermediate',
    focus: '하체 파워', cue: '점프하며 다리 교체. 균형 유지가 핵심',
    description: '런지의 폭발력 버전. 복싱 스텝 전환과 풋워크 파워에 직결.',
    steps: [
      '런지 자세에서 시작.',
      '폭발적으로 위로 점프하며 공중에서 다리 교체.',
      '반대 다리가 앞에 오도록 착지.',
      '착지 즉시 런지 하단까지 내림.',
      '리듬 유지하며 반복.',
    ],
    mistakes: ['착지가 쿵', '상체 흔들림', '다리 교체가 불완전'],
    imgQuery: 'jump lunge',
  },
  {
    id: 'burpee', name: '버피', category: 'bodyweight', venue: 'both', level: 'beginner',
    focus: '전신', cue: '스쿼트→플랭크→푸시업→점프. 한 동작으로 연결',
    description: '맨몸 HIIT의 왕. 짧은 시간에 최대 심박수를 끌어올린다.',
    steps: [
      '스쿼트로 앉으며 손을 바닥.',
      '두 발을 뒤로 점프해 플랭크.',
      '푸시업 한 번.',
      '두 발을 손 사이로 점프해 돌아옴.',
      '위로 크게 점프하며 박수.',
    ],
    mistakes: ['푸시업 생략 — 효과 반감', '착지가 무릎에 충격', '후반 자세가 무너짐'],
    imgQuery: 'burpee exercise',
  },
  {
    id: 'mountain_climber', name: '마운틴 클라이머', category: 'bodyweight', venue: 'both', level: 'beginner',
    focus: '코어·심폐', cue: '엉덩이 고정, 무릎만 가슴 쪽으로. 빠르게 리듬감 있게',
    description: '플랭크 + 카디오. 코어를 잡은 채 심박수를 끌어올린다.',
    steps: [
      '하이 플랭크 자세 (푸시업 시작 자세).',
      '한 무릎을 가슴 쪽으로 당김.',
      '빠르게 반대 다리와 교체.',
      '엉덩이 높이 유지 — 위아래로 흔들리지 않기.',
    ],
    mistakes: ['엉덩이가 올라가며 러닝 자세', '손목이 어깨보다 앞', '호흡 거침 — 의식적으로 조절'],
    imgQuery: 'mountain climber exercise',
  },
  {
    id: 'plank', name: '플랭크', category: 'bodyweight', venue: 'both', level: 'beginner',
    focus: '코어', cue: '몸 일직선. 허리 처지지 않게, 엉덩이 들리지 않게',
    description: '코어 고립 훈련. 복부·등·둔근 동시 자극. 복싱에서 흔들리지 않는 스탠스의 기반.',
    steps: [
      '팔꿈치를 어깨 바로 아래 위치.',
      '발끝·팔꿈치로 몸 지탱.',
      '엉덩이를 조여 일직선 유지.',
      '호흡은 자연스럽게.',
      '30-60초 유지.',
    ],
    mistakes: ['엉덩이 들림', '허리 처짐', '호흡 멈춤'],
    imgQuery: 'plank exercise',
  },
  {
    id: 'side_plank', name: '사이드 플랭크', category: 'bodyweight', venue: 'both', level: 'intermediate',
    focus: '복사근', cue: '팔꿈치-발까지 일직선. 엉덩이 떨어지지 않게 버티기',
    description: '복사근 고립. 훅·바디 공격의 회전력 기반.',
    steps: [
      '옆으로 누워 팔꿈치를 어깨 아래.',
      '발은 포개거나 앞뒤로.',
      '엉덩이를 들어올려 일직선.',
      '반대 팔은 천장 또는 허리.',
      '30초 유지, 반대쪽 교대.',
    ],
    mistakes: ['엉덩이 처짐', '어깨가 앞으로 말림', '목이 꺾임'],
    imgQuery: 'side plank',
  },
  {
    id: 'leg_raise', name: '레그 레이즈', category: 'bodyweight', venue: 'both', level: 'beginner',
    focus: '하복부', cue: '허리 바닥에 붙이기. 다리 내릴 때 반동 쓰지 말기',
    description: '복근 하부 집중. 바디샷 내구성과 펀치 파워에 기여.',
    steps: [
      '등을 대고 누워 허리를 바닥에 완전히 붙임.',
      '손은 엉덩이 옆 또는 허리 아래.',
      '다리를 뻗은 채 90도까지 들어올림.',
      '천천히 바닥 거의 닿기 전까지 내림.',
      '반동 없이.',
    ],
    mistakes: ['허리 뜸 — 요통 유발', '발이 바닥에 닿으며 쉼', '다리가 굽혀진 채 들기'],
    imgQuery: 'leg raise exercise',
  },
  {
    id: 'russian_twist', name: '러시안 트위스트', category: 'bodyweight', venue: 'both', level: 'beginner',
    focus: '복사근', cue: '상체 45도 뒤로 눕혀 좌우로 돌리기. 발은 가능하면 들기',
    description: '회전 코어 훈련. 훅의 근원.',
    steps: [
      '무릎을 굽혀 앉고 상체를 45도 뒤로 눕힘.',
      '가능하면 발을 바닥에서 띄움.',
      '손을 모아 좌우로 회전.',
      '회전은 어깨부터 — 허리만 돌리지 말 것.',
    ],
    mistakes: ['손만 흔들고 어깨가 안 돌아감', '등이 굽어짐', '호흡 멈춤'],
    imgQuery: 'russian twist exercise',
  },
  {
    id: 'v_up', name: '브이업', category: 'bodyweight', venue: 'both', level: 'intermediate',
    focus: '복근', cue: '손끝과 발끝이 V자로 만나게. 반동 없이 복근 힘으로만',
    description: '상복부·하복부 동시. 난이도 높은 복근 운동.',
    steps: [
      '등 대고 눕는다. 팔은 머리 위로.',
      '팔과 다리를 동시에 들어올려 V자.',
      '손끝이 발끝에 닿을 듯이.',
      '천천히 내려옴.',
    ],
    mistakes: ['목으로 당김', '반동 사용', '팔·다리 따로 움직임'],
    imgQuery: 'v up core exercise',
  },
  {
    id: 'bridge', name: '글루트 브릿지', category: 'bodyweight', venue: 'both', level: 'beginner',
    focus: '둔근', cue: '엉덩이 조이며 들어올리기. 허리로 들지 말 것',
    description: '둔근 활성화. 엉덩이 약한 사람의 파워 펀치는 없다.',
    steps: [
      '등 대고 누워 무릎을 굽힌다.',
      '발바닥을 바닥에 단단히.',
      '엉덩이를 조이며 들어올림 — 어깨-엉덩이-무릎 일직선.',
      '정점에서 1초 정지.',
      '천천히 내림.',
    ],
    mistakes: ['허리로 들어올림', '엉덩이를 완전히 짜지 않음', '발끝으로 밀기'],
    imgQuery: 'glute bridge',
  },
  {
    id: 'superman', name: '슈퍼맨', category: 'bodyweight', venue: 'both', level: 'beginner',
    focus: '허리·둔근', cue: '팔다리 동시에 살짝만 들기. 목 꺾지 말고 시선 바닥',
    description: '후면 체인 강화. 좋은 복싱 자세에 필수.',
    steps: [
      '엎드려 팔을 머리 위로 뻗음.',
      '팔·다리를 동시에 바닥에서 살짝만 들어올림.',
      '2초 유지 후 천천히 내림.',
      '시선은 바닥 유지.',
    ],
    mistakes: ['머리를 들어 목 과신전', '너무 높이 들어 요통', '호흡 멈춤'],
    imgQuery: 'superman exercise back',
  },
  {
    id: 'dips', name: '딥스 (의자)', category: 'bodyweight', venue: 'home', level: 'intermediate',
    focus: '삼두·흉근', cue: '의자·소파 모서리 사용. 어깨가 귀에 붙지 않게',
    description: '집에서 가능한 삼두 운동. 스트레이트 파워.',
    steps: [
      '의자 모서리에 손을 뒤로 받침.',
      '엉덩이를 의자에서 떼고 다리는 앞으로 뻗음.',
      '팔꿈치를 뒤로 굽혀 엉덩이를 내림.',
      '90도까지만 — 더 내리면 어깨 부상.',
      '삼두로 밀어 올라옴.',
    ],
    mistakes: ['어깨가 귀까지 올라옴', '팔꿈치 벌어짐', '너무 깊이 내려감'],
    imgQuery: 'bench dips tricep',
  },

  // ---- CONDITIONING
  {
    id: 'high_knees', name: '하이니', category: 'conditioning', venue: 'both', level: 'beginner',
    focus: '심폐', cue: '무릎이 허리 높이까지. 팔도 같이 복싱 가드 자세로 흔들기',
    description: '제자리 달리기 강화판. 복싱 리듬과 유사.',
    steps: [
      '제자리에서 빠르게 무릎을 허리 높이까지 올림.',
      '발은 앞쪽으로 착지.',
      '팔은 가드 자세 또는 달리기처럼.',
      '20-30초 전력, 10초 휴식 인터벌.',
    ],
    mistakes: ['무릎이 낮음', '뒤꿈치로 착지', '상체 앞으로 숙임'],
    imgQuery: 'high knees exercise',
  },
  {
    id: 'jumping_jacks', name: '점핑잭', category: 'conditioning', venue: 'both', level: 'beginner',
    focus: '심폐', cue: '부드럽게, 발목·무릎 충격 줄이기',
    description: '간단한 전신 카디오. 워밍업·피니셔 다용도.',
    steps: [
      '차렷 자세에서 점프하며 다리 벌리고 팔 위로.',
      '다시 점프하며 원위치.',
      '리듬감 있게 연속.',
    ],
    mistakes: ['쿵쿵 착지', '팔이 완전히 안 올라감', '호흡 리듬 깨짐'],
    imgQuery: 'jumping jacks',
  },
  {
    id: 'shuttle_run', name: '셔틀런 (왕복)', category: 'conditioning', venue: 'gym', level: 'intermediate',
    focus: '무산소', cue: '5-10m 왕복. 방향 바꿀 때 자세 낮추고 폭발적으로',
    description: '방향 전환 + 스프린트. 복싱 풋워크의 폭발력과 직결.',
    steps: [
      '5-10m 구간을 설정.',
      '한쪽에서 출발해 반대편까지 스프린트.',
      '반환점에서 자세 낮추고 방향 전환.',
      '10회 왕복 × 3세트, 세트 간 1분 휴식.',
    ],
    mistakes: ['방향 전환이 느림', '자세가 너무 높음', '반환점에서 미끄러짐'],
    imgQuery: 'shuttle run sprint',
  },
  {
    id: 'shadow_hiit', name: '섀도우 HIIT (30-30)', category: 'conditioning', venue: 'both', level: 'intermediate',
    focus: '복싱 심폐', cue: '30초 전력 콤보 - 30초 쉬운 스텝, 8-10세트',
    description: '복싱 특화 인터벌. 실제 라운드의 폭발-회복 사이클을 체내에 각인.',
    steps: [
      '30초: 최대 속도 콤보 섀도우.',
      '30초: 가벼운 스텝만 (완전 휴식 아님).',
      '8-10세트 반복.',
      '마지막 세트는 60초 풀아웃.',
    ],
    mistakes: ['쉬는 30초에 완전 멈춤', '폼 포기하고 속도만', '후반에 포기'],
    imgQuery: 'shadow boxing hiit',
  },
  {
    id: 'interval_run', name: '인터벌 러닝', category: 'conditioning', venue: 'gym', level: 'intermediate',
    focus: '심폐', cue: '1분 전력 - 2분 조깅, 5-8세트. 복싱 라운드 흉내',
    description: '복싱 라운드 구조를 모방한 야외 러닝.',
    steps: [
      '5분 가벼운 조깅 워밍업.',
      '1분 전력 질주.',
      '2분 조깅.',
      '5-8회 반복.',
      '5분 쿨다운 걷기.',
    ],
    mistakes: ['전력 구간에서 자세 무너짐', '워밍업·쿨다운 생략', '조깅 구간에서 멈추기'],
    imgQuery: 'interval running',
  },
  {
    id: 'stair_climb', name: '계단 오르기', category: 'conditioning', venue: 'gym', level: 'beginner',
    focus: '하체·심폐', cue: '한 계단씩 빠르게. 힘들면 두 계단씩으로 파워 훈련',
    description: '집 근처에서 가능한 하체 카디오. 넓적다리·종아리 동시 자극.',
    steps: [
      '한 계단씩 빠르게 오르기 10층.',
      '내려올 때는 천천히 — 무릎 보호.',
      '3세트 반복.',
      '숙달되면 두 계단씩 파워 버전.',
    ],
    mistakes: ['내려올 때 무릎에 충격', '발 전체 착지 대신 발끝만', '호흡 조절 실패'],
    imgQuery: 'stair climbing exercise',
  },

  // ---- COOLDOWN
  {
    id: 'static_stretch', name: '정적 스트레칭', category: 'cooldown', venue: 'both', level: 'beginner',
    focus: '회복', cue: '각 부위 30초 이상. 햄스트링·고관절·어깨 중점',
    description: '훈련 후 근육 이완. 유연성·회복을 위해 필수.',
    steps: [
      '햄스트링 스트레칭: 앉아서 다리 뻗고 상체를 앞으로 30초.',
      '고관절 스트레칭: 피전 포즈 각 30초.',
      '어깨: 한 팔을 가슴 앞으로 가져와 반대 팔로 당김.',
      '삼두: 손을 등 뒤로 보내 반대 손으로 팔꿈치 밀기.',
    ],
    mistakes: ['반동 사용', '통증까지 밀어붙임', '호흡 참기'],
    imgQuery: 'static stretching post workout',
  },
  {
    id: 'breath_recovery', name: '호흡 회복', category: 'cooldown', venue: 'both', level: 'beginner',
    focus: '회복', cue: '4초 들이마시고 6초 내쉬기. 심박수 안정화',
    description: '부교감 신경을 켜서 급속 회복을 유도. 다음 훈련 컨디션에 직접 영향.',
    steps: [
      '편한 자세로 앉거나 눕는다.',
      '코로 4초 들이마심.',
      '입으로 6초 내쉼.',
      '2-3분 반복.',
      '심박수가 분당 90 이하로 내려올 때까지.',
    ],
    mistakes: ['과호흡', '가슴으로만 호흡 — 복식호흡이 정답', '집중 안 하고 그냥 앉아있음'],
    imgQuery: 'breathing recovery meditation',
  },

  // ---- COMBINATION DRILLS
  {
    id: 'combo_basic_1_2', name: '기본 원투 (1-2)', category: 'combo', venue: 'both', level: 'beginner',
    focus: '기본 콤보', cue: '잽으로 길 열고 스트레이트로 끝내라',
    combo: [1, 2],
    description: '모든 콤비네이션의 기초. 잽이 거리와 리듬을 세팅하고 스트레이트가 대미지를 넣는다.',
    steps: [
      '1(잽): 앞손을 턱 높이에서 일직선으로 뻗는다.',
      '잽 회수와 동시에 뒷발 뒤꿈치를 돌린다.',
      '2(스트레이트): 힙 회전을 최대로 실어 뒷손을 쏜다.',
      '스트레이트 후 양손 모두 턱 앞 가드 위치로 복귀.',
    ],
    mistakes: ['잽과 스트레이트 사이가 끊김', '스트레이트에 힙이 안 실림', '가드 복귀 지연'],
    imgQuery: 'boxing jab cross combination',
  },
  {
    id: 'combo_1_1_2', name: '더블잽 크로스 (1-1-2)', category: 'combo', venue: 'both', level: 'beginner',
    focus: '리듬 변화', cue: '첫 잽은 견제, 두 번째 잽에 무게 실어 스트레이트 연결',
    combo: [1, 1, 2],
    description: '더블 잽으로 상대 가드 타이밍을 흔든 뒤 스트레이트를 꽂는다.',
    steps: [
      '1(잽): 가볍게 터치 수준, 거리 확인용.',
      '1(잽): 두 번째는 힘 30% 추가. 상대 가드를 밀어낸다.',
      '2(스트레이트): 잽 회수 동시에 풀 파워 크로스.',
      '마지막 펀치 후 사이드 스텝으로 각도 변경.',
    ],
    mistakes: ['두 잽이 같은 리듬 — 타이밍 변화가 포인트', '두 번째 잽이 너무 크게 들어감', '스트레이트 후 일직선 퇴각'],
    imgQuery: 'boxing double jab cross',
  },
  {
    id: 'combo_1_2_3', name: '잽-크로스-훅 (1-2-3)', category: 'combo', venue: 'both', level: 'beginner',
    focus: '3연타', cue: '직선-직선-곡선. 훅에서 체중이 앞발로 오며 파워 발생',
    combo: [1, 2, 3],
    description: '가장 자주 쓰이는 3연타. 직선으로 길을 연 후 각도를 바꿔 사이드를 친다.',
    steps: [
      '1(잽): 거리 셋업.',
      '2(스트레이트): 힙 회전으로 체중을 앞으로.',
      '3(리드훅): 스트레이트 후의 체중 이동을 그대로 살려 앞손 훅.',
      '훅 후 가드 복귀하며 한 발 뒤로 빠지기.',
    ],
    mistakes: ['훅에 팔만 쓰고 힙이 없음', '1-2 후 멈췄다가 3을 따로 침', '자세가 앞으로 넘어감'],
    imgQuery: 'boxing jab cross hook',
  },
  {
    id: 'combo_1_2_3_2', name: '잽-크로스-훅-크로스 (1-2-3-2)', category: 'combo', venue: 'both', level: 'intermediate',
    focus: '4연타 기본', cue: '마지막 크로스가 핵심. 훅 후 힙이 돌아오는 힘을 그대로 싣는다',
    combo: [1, 2, 3, 2],
    description: '4연타의 교과서. 훅 후 자연스러운 힙 리턴을 활용한 마무리 크로스.',
    steps: [
      '1-2: 기본 잽-크로스.',
      '3(리드훅): 체중을 앞발로 옮기며 훅.',
      '2(크로스): 훅 후 힙이 돌아오는 반동을 실어 마무리 크로스.',
      '마지막 크로스 후 즉시 가드 + 사이드 스텝.',
    ],
    mistakes: ['3번째 훅에서 밸런스 무너짐', '마지막 크로스가 팔로만 나감', '리듬이 일정함 — 속도 변화 필요'],
    imgQuery: 'boxing four punch combination',
  },
  {
    id: 'combo_1_6_3_2', name: '잽-리어어퍼-훅-크로스 (1-6-3-2)', category: 'combo', venue: 'both', level: 'intermediate',
    focus: '레벨 체인지', cue: '잽 후 몸을 낮추며 어퍼컷, 올라오며 훅-크로스',
    combo: [1, 6, 3, 2],
    description: '상-하-측-직의 각도 변화. 상대가 예측하기 가장 어려운 공격 패턴 중 하나.',
    steps: [
      '1(잽): 스탠딩 높이에서 잽으로 시선 고정.',
      '6(리어 어퍼컷): 무릎을 굽혀 레벨을 낮추며 뒷손 어퍼컷.',
      '3(리드훅): 올라오면서 체중 이동을 살려 앞손 훅.',
      '2(크로스): 마무리 크로스 → 즉시 빠지기.',
    ],
    mistakes: ['어퍼컷에서 머리가 앞으로 빠짐', '레벨 체인지 없이 높이가 같음', '훅이 어퍼컷과 시간차 없이 나감'],
    imgQuery: 'boxing uppercut hook combination',
  },
  {
    id: 'combo_1_2_5_2', name: '잽-크로스-리드어퍼-크로스 (1-2-5-2)', category: 'combo', venue: 'both', level: 'intermediate',
    focus: '인사이드 공격', cue: '크로스로 가드 열고 어퍼컷으로 아래서 올려치기',
    combo: [1, 2, 5, 2],
    description: '직선 공격으로 거리 좁힌 후 어퍼컷으로 가드 아래를 뚫고 크로스로 마무리.',
    steps: [
      '1-2: 잽-크로스로 상대 가드를 열리게.',
      '5(리드 어퍼컷): 무릎 굽히며 앞손 어퍼컷을 가드 사이로.',
      '2(크로스): 어퍼컷의 올라가는 힘을 이용해 마무리 크로스.',
      '크로스 후 가드 + 뒤로 빠지기.',
    ],
    mistakes: ['어퍼컷 궤적이 너무 큼', '인사이드 거리에서 가드 놓침', '마지막 크로스가 약함'],
    imgQuery: 'boxing inside fighting combination',
  },
  {
    id: 'combo_3_2_3', name: '훅-크로스-훅 (3-2-3)', category: 'combo', venue: 'both', level: 'intermediate',
    focus: '좌우 교차', cue: '좌-우-좌 삼연타. 힙이 시계추처럼 좌우로 돌아야 한다',
    combo: [3, 2, 3],
    description: '근거리에서 좌우를 번갈아 치는 인파이팅 콤보. 힙의 좌우 진자 운동이 핵심.',
    steps: [
      '3(리드훅): 근거리에서 앞손 훅.',
      '2(크로스): 훅 후 힙 리턴을 실어 크로스.',
      '3(리드훅): 다시 힙이 돌아오는 힘으로 두 번째 훅.',
      '세 펀치 사이에 끊김이 없어야 함 — 하나의 흐름.',
    ],
    mistakes: ['팔로만 치고 힙이 안 돌아감', '발이 고정된 채로', '두 번째 훅에 힘이 없음'],
    imgQuery: 'boxing hook cross hook',
  },
  {
    id: 'combo_1_2_1_2', name: '더블 원투 (1-2-1-2)', category: 'combo', venue: 'both', level: 'beginner',
    focus: '연속 직선', cue: '첫 원투는 테스트, 두 번째 원투에 파워를 몰아넣어라',
    combo: [1, 2, 1, 2],
    description: '같은 콤보를 반복하되 강도를 다르게. 첫 번째는 견제, 두 번째에 풀 파워.',
    steps: [
      '1-2: 가벼운 잽-크로스 (속도 60%, 파워 40%).',
      '1-2: 즉시 같은 콤보를 풀 파워 (속도 90%, 파워 100%).',
      '강약 대비가 리듬의 핵심.',
      '두 번째 크로스 후 반드시 사이드 스텝.',
    ],
    mistakes: ['두 원투가 같은 강도', '두 번째에서 자세 무너짐', '빠져나오기를 잊음'],
    imgQuery: 'boxing double one two',
  },
  {
    id: 'combo_1_2_3_4_2', name: '5연타 (1-2-3-4-2)', category: 'combo', venue: 'both', level: 'advanced',
    focus: '장타 콤보', cue: '5개를 하나의 숨에. 3-4 훅 교차 후 크로스 마무리',
    combo: [1, 2, 3, 4, 2],
    description: '5연타 풀 콤보. 양손 훅 교차 후 마무리 크로스. 지구력과 밸런스가 동시에 필요.',
    steps: [
      '1(잽): 거리 진입.',
      '2(크로스): 힙 풀 로테이션.',
      '3(리드훅): 체중 앞으로.',
      '4(리어훅): 체중 뒤로 돌며 뒷손 훅.',
      '2(크로스): 마무리. 5번째까지 폼 유지가 핵심.',
    ],
    mistakes: ['4번째부터 자세 무너짐', '가드가 풀리며 카운터에 취약', '마지막 크로스에 힘이 없음'],
    imgQuery: 'boxing five punch combination',
  },
  {
    id: 'combo_1_2_3_6_3_2', name: '6연타 (1-2-3-6-3-2)', category: 'combo', venue: 'both', level: 'advanced',
    focus: '풀 콤보', cue: '직-직-곡-하-곡-직. 모든 각도를 한 세트에 담아라',
    combo: [1, 2, 3, 6, 3, 2],
    description: '직선·곡선·어퍼컷을 모두 섞은 풀 콤비네이션. 실전에서 상대를 완전히 압도하는 콤보.',
    steps: [
      '1-2: 잽-크로스로 길 열기.',
      '3(리드훅): 사이드 타격.',
      '6(리어 어퍼컷): 레벨 낮추며 상대 턱 아래로.',
      '3(리드훅): 올라오면서 다시 사이드.',
      '2(크로스): 파워 크로스 마무리 → 즉시 빠지기.',
    ],
    mistakes: ['중간에 리듬이 끊김', '어퍼컷에서 밸런스 잃음', '후반 3개 펀치에 힘 분배 실패'],
    imgQuery: 'boxing six punch combination',
  },
  {
    id: 'combo_2_3_2', name: '크로스-훅-크로스 (2-3-2)', category: 'combo', venue: 'both', level: 'intermediate',
    focus: '카운터 콤보', cue: '상대 잽을 슬립 후 크로스로 시작하는 카운터 공격',
    combo: [2, 3, 2],
    description: '상대 잽을 피한 뒤 리드하는 카운터 콤보. 크로스로 시작하는 공격적 패턴.',
    steps: [
      '슬립 후 즉시 2(크로스): 카운터 크로스.',
      '3(리드훅): 크로스 후 힙 리턴으로 훅.',
      '2(크로스): 마무리.',
      '카운터이므로 진입 타이밍이 생명.',
    ],
    mistakes: ['슬립 없이 크로스부터 시작 — 카운터 맞음', '진입 거리 계산 실패', '마지막 크로스가 텔레그래프됨'],
    imgQuery: 'boxing counter combination',
  },
  {
    id: 'combo_body_1_2b_3b_2', name: '바디 콤보 (1-2b-3b-2)', category: 'combo', venue: 'both', level: 'intermediate',
    focus: '바디 공격', cue: '잽으로 시선 올리고 크로스-훅은 바디로. 마지막에 머리로',
    combo: [1, '2b', '5b', 2],
    description: '헤드-바디-바디-헤드. 상대 가드를 위아래로 분산시키는 전략적 콤보.',
    steps: [
      '1(잽): 머리 높이 — 상대 시선을 위로 유도.',
      '2b(바디 크로스): 자세 낮추며 상대 솔라플렉서스.',
      '3b(바디 어퍼): 간 부위 타격.',
      '2(크로스): 올라오면서 머리로 마무리 크로스.',
    ],
    mistakes: ['바디 치면서 머리 가드 풀림', '레벨 체인지가 없이 같은 높이', '올라올 때 느림 — 카운터 위험'],
    imgQuery: 'boxing body combination',
  },
  {
    id: 'combo_5_6_3_2', name: '더블어퍼-훅-크로스 (5-6-3-2)', category: 'combo', venue: 'both', level: 'advanced',
    focus: '인파이팅', cue: '양손 어퍼컷으로 가드 들어올린 후 훅-크로스 마무리',
    combo: [5, 6, 3, 2],
    description: '극근거리 인파이팅. 어퍼컷으로 상대 가드를 위로 밀어올린 뒤 사이드-직선으로 마무리.',
    steps: [
      '5(리드 어퍼컷): 상대 가드 아래에서 밀어올리기.',
      '6(리어 어퍼컷): 반대 손으로 즉시 두 번째 어퍼컷.',
      '3(리드훅): 상대 가드가 올라간 틈에 사이드 공격.',
      '2(크로스): 마무리 파워 크로스.',
    ],
    mistakes: ['어퍼컷이 팔로만 나감 — 다리 스프링 필수', '가드가 완전히 풀림', '두 어퍼컷 사이가 느림'],
    imgQuery: 'boxing uppercut combination infighting',
  },
  {
    id: 'combo_1_2_slip_2_3', name: '원투-슬립-크로스-훅 (1-2-슬립-2-3)', category: 'combo', venue: 'both', level: 'advanced',
    focus: '공방전환', cue: '공격 후 슬립으로 카운터 피한 뒤 다시 공격. 실전 콤보',
    combo: [1, 2, 'SL', 2, 3],
    description: '공격-방어-공격의 전환 콤보. 실전 리듬 그 자체.',
    steps: [
      '1-2: 잽-크로스 던짐.',
      'SL(슬립): 상대 카운터를 예상하고 즉시 바깥쪽으로 슬립.',
      '2(크로스): 슬립의 체중이동을 그대로 실어 카운터 크로스.',
      '3(훅): 마무리 훅 → 빠지기.',
    ],
    mistakes: ['슬립 타이밍이 느림', '슬립 후 체중이 무너짐', '공격-방어 전환에서 가드 놓침'],
    imgQuery: 'boxing slip counter combination',
  },
  {
    id: 'combo_1_5b_2_3', name: '잽-바디어퍼-크로스-훅 (1-5b-2-3)', category: 'combo', venue: 'both', level: 'intermediate',
    focus: '상하 교란', cue: '잽 후 바디로 내려갔다가 올라오며 직선-곡선 연타',
    combo: [1, '5b', 2, 3],
    description: '수직 교란 콤보. 상하 변화로 상대 방어를 분열시킨다.',
    steps: [
      '1(잽): 머리 라인 잽.',
      '3b(바디 어퍼): 자세 낮추며 간 부위.',
      '2(크로스): 올라오면서 머리로 크로스.',
      '3(리드훅): 마무리 훅.',
    ],
    mistakes: ['바디에서 올라올 때 가드가 내려가 있음', '레벨 체인지가 너무 느림', '바디어퍼이 너무 약하게 터치만'],
    imgQuery: 'boxing body head combination',
  },
  {
    id: 'combo_1_2_weave_3_2', name: '원투-위브-훅-크로스 (1-2-위브-3-2)', category: 'combo', venue: 'both', level: 'advanced',
    focus: '위브 카운터', cue: '원투 던지고 위브로 잠수, 올라오며 훅-크로스',
    combo: [1, 2, 'WV', 3, 2],
    description: '공격 후 U턴 위브로 상대 카운터를 피하고 다시 올라가며 마무리.',
    steps: [
      '1-2: 잽-크로스.',
      'WV(위브): 상체를 U자로 낮추며 상대 리턴훅을 피한다.',
      '3(리드훅): 위브에서 올라오는 탄력을 실어 훅.',
      '2(크로스): 최종 마무리.',
    ],
    mistakes: ['위브가 너무 깊어 올라오기 힘듦', '위브 중 균형 잃음', '훅에 탄력이 안 실림'],
    imgQuery: 'boxing weave counter',
  },

];

// 펀치 넘버 범례
window.PUNCH_LEGEND = {
  1:    { name: '잽',           short: 'JAB',      hand: 'lead',  type: 'straight', level: 'head' },
  2:    { name: '스트레이트',    short: 'CROSS',    hand: 'rear',  type: 'straight', level: 'head' },
  3:    { name: '리드 훅',      short: 'L.HOOK',   hand: 'lead',  type: 'hook',     level: 'head' },
  4:    { name: '리어 훅',      short: 'R.HOOK',   hand: 'rear',  type: 'hook',     level: 'head' },
  5:    { name: '리드 어퍼컷',   short: 'L.UPPER',  hand: 'lead',  type: 'uppercut', level: 'head' },
  6:    { name: '리어 어퍼컷',   short: 'R.UPPER',  hand: 'rear',  type: 'uppercut', level: 'head' },
  '2b': { name: '바디 크로스',   short: 'B.CROSS',  hand: 'rear',  type: 'straight', level: 'body' },
  '5b': { name: '바디 리드어퍼', short: 'B.L.UP',   hand: 'lead',  type: 'uppercut', level: 'body' },
  '6b': { name: '바디 리어어퍼', short: 'B.R.UP',   hand: 'rear',  type: 'uppercut', level: 'body' },
  'SL': { name: '슬립',         short: 'SLIP',     hand: 'none',  type: 'defense',  level: 'none' },
  'WV': { name: '위브',         short: 'WEAVE',    hand: 'none',  type: 'defense',  level: 'none' },
  'DK': { name: '더킹',         short: 'DUCK',     hand: 'none',  type: 'defense',  level: 'none' },
  'SB': { name: '스텝백',       short: 'S.BACK',   hand: 'none',  type: 'defense',  level: 'none' },
  'PV': { name: '피벗',         short: 'PIVOT',    hand: 'none',  type: 'defense',  level: 'none' },
};

// 오늘의 콤비네이션 — 긴 실전 콤보 (매일 1개 추천)
window.DAILY_COMBOS = [
  {
    name: '더킹 카운터 스톰',
    combo: [1, 2, 'DK', 5, 6, 3, 2],
    cue: '원투로 진입 → 더킹으로 카운터 회피 → 어퍼-어퍼-훅-크로스 폭풍',
    focus: '공방전환',
    difficulty: 'ADVANCED',
  },
  {
    name: '바디 브레이커',
    combo: [1, '5b', 2, 'DK', '2b', 3, 2],
    cue: '잽-바디어퍼으로 숙이게 만들고 더킹 후 바디크로스-훅-크로스 마무리',
    focus: '바디 파괴',
    difficulty: 'ADVANCED',
  },
  {
    name: '슬립 투 킬',
    combo: [1, 2, 'SL', 2, 3, 'SL', 2, 3, 2],
    cue: '원투-슬립-크로스-훅, 다시 슬립-크로스-훅-크로스. 슬립마다 카운터',
    focus: '슬립 카운터 연쇄',
    difficulty: 'EXPERT',
  },
  {
    name: '레벨 체인지 러시',
    combo: [1, 2, '5b', 6, 3, 'DK', 5, 2],
    cue: '직선-바디어퍼-어퍼-훅 → 더킹 → 어퍼-크로스. 위-아래-위 교란',
    focus: '레벨 체인지',
    difficulty: 'ADVANCED',
  },
  {
    name: '위브 앤 디스트로이',
    combo: [1, 2, 'WV', 3, 4, 'WV', 5, 6, 2],
    cue: '원투-위브-좌훅-우훅-위브-좌어퍼-우어퍼-크로스. 위브마다 폭격',
    focus: '위브 후 연타',
    difficulty: 'EXPERT',
  },
  {
    name: '더블 더킹 콤보',
    combo: [1, 'DK', 5, 2, 3, 'DK', 6, 3, 2],
    cue: '잽-더킹-어퍼-크로스-훅, 다시 더킹-어퍼-훅-크로스. 더킹이 리듬',
    focus: '더킹 활용',
    difficulty: 'ADVANCED',
  },
  {
    name: '피벗 앵글 체인지',
    combo: [1, 2, 3, 'PV', 2, '5b', 6, 2],
    cue: '원투-훅 후 피벗으로 각도 바꾸고 크로스-바디어퍼-어퍼-크로스',
    focus: '각도 변환',
    difficulty: 'ADVANCED',
  },
  {
    name: '풀 아스날',
    combo: [1, 1, 2, 'SL', 2, 3, 'DK', 5, 6, 3, 2],
    cue: '더블잽-크로스-슬립-크로스-훅-더킹-더블어퍼-훅-크로스. 11연타 풀세트',
    focus: '올라운드',
    difficulty: 'EXPERT',
  },
  {
    name: '인파이터 드릴',
    combo: [5, 6, 3, 'WV', 5, '5b', 4, 2],
    cue: '어퍼-어퍼-훅-위브-어퍼-바디어퍼-리어훅-크로스. 근거리 압도',
    focus: '인파이팅',
    difficulty: 'ADVANCED',
  },
  {
    name: '스텝백 카운터',
    combo: [1, 2, 'SB', 1, 2, 3, 'DK', 6, 3, 2],
    cue: '원투 던지고 스텝백으로 거리 만든 뒤 재진입 잽-크로스-훅-더킹-어퍼-훅-크로스',
    focus: '거리 조절',
    difficulty: 'EXPERT',
  },
  {
    name: '사우스포 킬러',
    combo: [2, 3, 2, 'PV', 1, '2b', 5, 3, 2],
    cue: '크로스-훅-크로스 후 피벗으로 사이드 이동, 잽-바디-어퍼-훅-크로스',
    focus: '앵글 공격',
    difficulty: 'ADVANCED',
  },
  {
    name: '프레셔 파이터',
    combo: [1, 2, 1, 3, 'DK', 5, 6, 'WV', 3, 4, 2],
    cue: '잽-크로스-잽-훅-더킹-더블어퍼-위브-좌훅-우훅-크로스. 쉬지 않는 압박',
    focus: '프레셔',
    difficulty: 'EXPERT',
  },
  {
    name: '히트 앤 무브',
    combo: [1, 2, 'SB', 1, 'SL', 2, 3, 'PV', 2],
    cue: '원투-빠지기-잽-슬립-크로스-훅-피벗-크로스. 치고 빠지기의 정석',
    focus: '아웃복싱',
    difficulty: 'ADVANCED',
  },
  {
    name: '더킹 훅 러시',
    combo: [1, 'DK', 3, 4, 'DK', 3, 4, 2],
    cue: '잽-더킹-좌훅-우훅-더킹-좌훅-우훅-크로스. 더킹 후 훅 연타',
    focus: '훅 연타',
    difficulty: 'ADVANCED',
  },
  {
    name: '카오스 콤보',
    combo: [1, 2, 'WV', 6, 3, 'SL', 2, '5b', 'DK', 5, 2],
    cue: '직선-위브-어퍼-훅-슬립-크로스-바디-더킹-어퍼-크로스. 모든 각도',
    focus: '불규칙 패턴',
    difficulty: 'EXPERT',
  },
  {
    name: '심플 킬러',
    combo: [1, 2, 'DK', 2, 3, 2],
    cue: '원투-더킹-크로스-훅-크로스. 심플하지만 파괴적',
    focus: '효율적 콤보',
    difficulty: 'INTERMEDIATE',
  },
  {
    name: '어퍼컷 시티',
    combo: [1, 5, 2, 6, 'DK', 5, 6, 3, 2],
    cue: '잽-리드어퍼-크로스-리어어퍼-더킹-더블어퍼-훅-크로스. 어퍼컷 축제',
    focus: '어퍼컷',
    difficulty: 'ADVANCED',
  },
  {
    name: '디펜스 투 오펜스',
    combo: ['SL', 2, 'WV', 3, 'DK', 5, 6, 2],
    cue: '슬립-크로스-위브-훅-더킹-더블어퍼-크로스. 방어로 시작, 공격으로 끝',
    focus: '방어 시작 콤보',
    difficulty: 'ADVANCED',
  },
  {
    name: '트리플 레벨',
    combo: [1, 2, '5b', '2b', 'DK', 5, 3, 2],
    cue: '잽-크로스(헤드)-바디어퍼-바디크로스(바디)-더킹-어퍼(아래)-훅-크로스(헤드). 3단 높이',
    focus: '3레벨 공격',
    difficulty: 'ADVANCED',
  },
  {
    name: '파이널 라운드',
    combo: [1, 1, 2, 3, 'DK', 5, 6, 'WV', 3, 4, '2b', 5, 2],
    cue: '더블잽-크로스-훅-더킹-더블어퍼-위브-훅-훅-바디-어퍼-크로스. 13연타 마무리',
    focus: '올아웃',
    difficulty: 'EXPERT',
  },
];

// 오늘의 콤보 가져오기 (날짜 기반 + 셔플 오프셋)
window._dailyComboOffset = 0;
window.getDailyCombo = function() {
  const today = new Date();
  const dayIndex = (Math.floor(today.getTime() / 86400000) + window._dailyComboOffset) % window.DAILY_COMBOS.length;
  return window.DAILY_COMBOS[dayIndex];
};
window.shuffleDailyCombo = function() {
  window._dailyComboOffset = (window._dailyComboOffset + 1) % window.DAILY_COMBOS.length;
  return window.getDailyCombo();
};

// 경력별 볼륨 파라미터
window.VOLUME_PARAMS = {
  beginner:     { rounds: 3,  roundMin: 2, restSec: 60, reps: { low: 8,  mid: 12, high: 15 }, totalExercises: 5 },
  intermediate: { rounds: 6,  roundMin: 3, restSec: 60, reps: { low: 12, mid: 15, high: 20 }, totalExercises: 7 },
  advanced:     { rounds: 10, roundMin: 3, restSec: 45, reps: { low: 15, mid: 20, high: 25 }, totalExercises: 9 },
};

// 카테고리 라벨 (표시용)
window.CATEGORY_LABELS = {
  warmup: '워밍업',
  shadow: '섀도우',
  bag: '샌드백',
  combo: '콤비네이션',
  sparring: '스파링',
  bodyweight: '맨몸 운동',
  conditioning: '컨디셔닝',
  cooldown: '쿨다운',
};

// 운동 조회 헬퍼
window.getExerciseById = function(id) {
  return window.EXERCISES.find(e => e.id === id);
};

// Unsplash 참고 이미지 URL
window.getExerciseImageUrl = function(exercise, size) {
  size = size || '400x300';
  const query = encodeURIComponent(exercise.imgQuery || exercise.name);
  return 'https://source.unsplash.com/' + size + '/?' + query;
};
